This time, my adventurer card random tests alone were able to test 28.8% of lines, at 27.1% of branches, which consists of over a quarter of all of dominion.c. Additionally, my smithy card random tests were able to test 29.52%, but a lot of these were overlapping lines. For example, I was able to call some of the initialization functions 3,000 times, such as setting up the random number generator. Also, because I initialized the game with random kingdom cards, the decks with random choices from all the possible cards, and a random number of players, I was able to get explore many more branches, including all of the supply initialization steps and player shuffling and drawing steps. 

From my adventurer card tests, I was able to learn a couple of very significant things. When I first started doing the random tests, I was not able to exceed more than 15 tests consistently without running into some of infinite loop error. At first, I had thought that it would get caught in an infinite loop only if there were absolutely no treasure cards in the hand, deck, and discard pile. Then, after forcing each random deck to have at least one treasure card, I realized that the original adventurer function would still fail to work because 

Then, from my adventurer statistics, I was able to visualize just how difficult to detect some errors were relative to others. For example, it was fairly easy to detect that the cardCount simply did not change at all (in 3,000 of the 3,000 tests). On the other hand, some of the other card statistics were more subtle.  For example, the wrong number of treasure cards was added to the hand only 2,421 out of 3,000 times. Because my errors induce the player to keep all the non-treasure cards that they draw, if the player draws only treasure cards (which apparently happened about 580 times), then no error is registered. Also, the wrong number of treasure cards were added to the hand only 2,081 times. In theory, in my function, the wrong number of treasure cards would be added whenever a non-treasure card was revealed, but this seems not to have happened 1 in 3 times. However, this inordinately high likelihood is probably because I specifically added treasure cards to the deck if there weren’t any randomly generated (to avoid infinite loops), which increased the likelihood that the first few cards would be treasure cards. 

Unfortunately, my random smithy card tests had much more enigmatic results. For example, there was a wrong hand count in 2,998 out of the 3,000 results, which left only 2 tests with correct results, an astronomically low number. However, this is because there were 2 major confounding factors. First, the number of cards added to the hand were essentially randomized by my bug, which set the count of cards to be added to be an uninitialized variable. Second, even if the correct number of cards were added to the hand, the cards discarded from the hand were counfounded by the second major bug, which is that the hand position of the card to be discarded and the current player are switched, which also explains why there was a wrong discard count of 2,943 out of 3,000 and wrong deck count of 2,808 out of 3,000. 

More statistically interesting errors were the number of times the hand, deck, or discard as changed in other players, a surprisingly low number of only 1,263 out of 3,000 (considering that the handPos and current player are switched.  Additionally, the total number of cards in the hand, deck, and discard pile changed was only 867 out of 3,000.  However, because these were only affected by the second bug, they make sense. Since there are a maximum of 4 players in the game, but the uninitialized variable allows for the deck count of 1-10 to be increased by an unknown number, the bug wouldn’t actually affect most players if the card was a high enough hand position. 









