James Guerra Assignment 4

File 'randomtestcard.c'
Lines executed:86.21% of 29
Branches executed:100.00% of 6
Taken at least once:50.00% of 6
Calls executed:81.25% of 16
Creating 'randomtestcard.c.gcov'

File 'randomtestadventure.c'
Lines executed:86.11% of 36
Branches executed:100.00% of 16
Taken at least once:56.25% of 16
Calls executed:77.78% of 18

Both of these files are an improvement over the coverage in our unit tests, with 100% 
branch coverage and a small increase in line coverage.  The increase in coverage is possibly
due to the element of randomness included into the test, with multiple player numbers, hands 
and seeds being generated by the tests, increasing the amount of code being used by the test suite. 